version: 1.0.0.{build}.{branch}

nuget:
  account_feed: true
  
environment:
    CORDOVA_CACHE: C:\projects\mobilekidsidapp\cordova_cache
    ANDROID_HOME: C:\Program Files (x86)\Android\android-sdk
    JAVA_HOME: C:\Program Files (x86)\Java\jdk1.7.0_55


init:
 - git config --global core.autocrlf true
 
services:
  - mssql2014
  
install:
 - cmd: nuget sources add -Name api.nuget.org -Source https://api.nuget.org/v3/index.json
 
before_build:
 - cmd: cd  .\src\MCM.KidsIdApp
 - cmd: npm install

build_script:
 - cmd: .\node_modules\.bin\gulp
 
